version: 2
jobs:
  ruby-2.6:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle
          command: |
            gem install bundler
            bundle check --path vendor/bundle || bundle install --deployment
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: RSpec
          command: bundle exec rspec
workflows:
  version: 2
  test-rubies:
    jobs:
      - ruby-2.6
