name: Test and Publish
on:
  pull_request:
    branches: ["*"]
  push:
    branches: [master]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # https://bundler.io/compatibility.html
        ruby:
          - version: ruby-3.4
            bundler: "2.6"
          - version: ruby-3.3
            bundler: "2.5"
    name: ${{ matrix.ruby.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.version }}
      - name: Install bundler
        run: gem install bundler --version ${{ matrix.ruby.bundler }}
      - name: Install gems
        run: bundle install
      - name: Run tests
        run: bundle exec rspec

  publish:
    name: Publish to GitHub Packages
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.4

      - name: Configure gem credentials
        run: |
          mkdir -p ~/.gem
          cat > ~/.gem/credentials << EOF
          ---
          :github: Bearer ${GITHUB_TOKEN}
          EOF
          chmod 0600 ~/.gem/credentials
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build gem
        run: gem build *.gemspec

      - name: Publish to GitHub Packages
        run: |
          gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
